### ISSUE TITLE
How to replace the fiber to realize the interaction between the two pulses?

### ISSUE THREAD

**Issue by shenhaii** [omelchert/py-fmas#1]
I want to incident two pulses in the mid-infrared band to observe the interaction between the two pulses, so I need to replace the fiber. But I have the following questions, I hope to get your answer.
1、In your program about the interaction of two pulses（g_specialized_model_NLPM.py）, you used the expansion coefficient, but in your paper in 2020（All-optical supercontinuum switching）, you gave the second to eleventh order dispersion parameters. I don't understand the relationship between them. Can I replace the expansion coefficient in the program with the dispersion coefficient?
2、I want to incident two group velocity matched pulses (such as 5760nm and 3900nm) in the optical fiber. These two pulses have different dispersion coefficients at their respective wavelengths. How can I reflect them in the program?

**Comment by omelchert** [comment]
Hey shenhaii,

thank you for your interest in using the py-fmas package for your numerical 
experiments. I will include a list of frequently asked questions to the project 
page and add an anonymous version of your questions to that list. So, thank 
you for your input!  Below you find answers to your two questions. 

**Answer to question 1:**

The expansion coefficients c_n are those of a Taylor-expansion of the
propagation constant. They are related to the dispersion parameters beta_n in
the form c_n = beta_n/n!. 

In lines 335-381 of module py-fmas/fmas/propagation_constant.py you will find
the function "define_beta_fun_PCF_Ranka2000". It implements an exemplary PCF
for which the dispersion parameters are listed in [J. M. Dudley, G. Genty, S.
Coen, Supercontinuum generation in photonic crystal fiber, Rev. Mod. Phys. 78
(2006) 1135].  The function demonstrates how the expansion coefficients for the
numpy function "poly1d" are obtained from the dispersion parameters. 

Be aware of a technical detail: the numpy function "poly1d", which generates a
polynomial for a given sequence of expansion coefficients, expects the
coefficients to be supplied in reverse order. Therefore, the highest order
coefficient is the first in the list.

**Answer to question 2:**

The py-fmas code performs numerical calculations based on a frequency dependent
propagation constant "beta". Consider two pulses with angular frequencies "w1"
and "w2". The "frequency-local" dispersion parameters for pulse 1 are
determined by a Taylor expansion of "beta" about "w1", which will give you one
set of numbers. The dispersion parameters for pulse 2 are determined by a
Taylor expansion of "beta" about "w2", which yields a second set of numbers.

If I understood correctly you have these two sets of numbers that describe the
propagation constant at the two frequencies "w1" and "w2". If you would like to
use the py-fmas code, you will need to first figure out what the frequency
dependent propagation constant "beta" is. This would be the adequate way to 
represent the dispersive properties of the medium. You then have the choice to 
represent this in any way you fancy. For example, you could use a Taylor approximant
of "beta" as demonstrated in function  "define_beta_fun_PCF_Ranka2000".

Best wishes
Oliver

**Comment by shenhaii** [comment]
Thank you very much for your reply, it is very helpful to me, I am very grateful, I will refer to your answer and your code about two pulse interaction and four pulse interaction to modify my code.
