### ISSUE TITLE
Adding noise and calculating the coherence

### ISSUE THREAD

**Issue by KdaerMed2018** [omelchert/py-fmas#3]
First I would to thank the authors for their remarkable effort and for making it publicly accessible
My question is the following:
Considering simulating supercontinuum generation in optical fibers. How to add noise to the initial pulse and calculate the first order coherence. It will very nice if you add a small example of that.
Thank you again

**Comment by omelchert** [comment]
Thank you for this suggestion. A small extension module allowing to add noise to the initial condition and calculate coherence properties is already underway! I will keep you posted on the progress.

**Comment by KdaerMed2018** [comment]
looking forward to your updates
All the best

**Comment by omelchert** [comment]
I prepared a small extension module implementing the widely used generalized nonlinear Schrödinger equation, several models of input pulse quantum noise, and functions for assessing interpulse and intrapulse coherence of ensembles of spectra.

You can find the extension module, called GNLStools, under [this link](https://github.com/omelchert/GNLStools.git). Examples that demonstrate how to use the model on its own or as extension of py-fmas, are provided along with the code.

A writeup with focus on the implementation of input pulse quantum noise is available [here](https://arxiv.org/abs/2206.07526).

I enjoyed working on this tiny module and hope you and other interested users find it useful and benefit from the functionality it adds to the py-fmas package.

**Comment by KdaerMed2018** [comment]
Well done
thank you so much for your efforts
